### PR TITLE
Add workflow to auto-generate wheels for Linux, Windows and Mac OS

### PR DESCRIPTION
**Pull request by nanna7077**
Hi! I have added a workflow that generates wheels for all platforms automatically on all push's and pull request's. I feel that this would make it easier to install it.

The action generates a single artifacts zip file which can be manually downloaded and added to release (or chained to do that automatically too but that would get require token to be added to repo secrets)

### CODE REVIEW

**Comment by cheofusi** [comment]
Hi @nanna7077,

Thanks for this pull request. I'll merge some fixes and your branch over the weekend and hopefully get 0.1.7 out by the 1st.

**Comment by nanna7077** [comment]
Welcome and looking forward to it!

**Comment by DataExplorerUser** [comment]
Any updates on this? 

I'm trying to pip install on Windows and Python 3.8, but it doesn't install due to an error.

just_playback looks very promising. I have used PyMiniAudio, which is also based on Miniaudio and works well, in a project but the justplay API looks more straightforward and offers a bit more functionality.

It would also be useful if you add a license to just_playback, so that people can include into their projects. Maybe you could use the Miniaudio license (https://github.com/mackron/miniaudio/blob/master/LICENSE) for this project as well.

Thanks!

**Review by cheofusi — CHANGES_REQUESTED** [review]
Hi,
I think it would be great if you

- use the latest versions of each action
- change the `macOS-10.15` label to `macos-11`
- enable cross builds for `universal2` and `arm64` wheels on macos. See [this](https://cibuildwheel.readthedocs.io/en/stable/faq/#apple-silicon)

**Review by cheofusi — COMMENTED** [review]
Thank you for the changes.

I think it'd be better to use a single job like the [first one](https://github.com/cheofusi/just_playback/pull/15/commits/050841ecfb71eef894b1bc0723a727d9e9ced9a4) with an additional conditional step such as
```
- name: Build macOS wheels
  uses: pypa/cibuildwheel@v2.8.1
  env:
     CIBW_ARCHS_MACOS: x86_64 arm64
  if: ${{ matrix.os}} == 'macos-11'
```
Also I think we should ditch cross builds for universal binaries for now. They don't seem to work well as cffi doesn't provide them.

**Pull request merged**
